import Image from "next/image";
import type { ReactNode } from "react";
import { ArrowRight, Search, Sparkles } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput } from "@/components/ui/input-group";

export function HomeContent({ children }: { children: ReactNode }) {
  return <main className="flex flex-1 flex-col overflow-hidden"><div className="mx-auto flex w-full max-w-[1440px] flex-col gap-14 px-4 py-5 sm:px-6 sm:py-8 lg:gap-20 lg:px-10 lg:py-10"><section className="relative isolate overflow-hidden rounded-3xl border bg-home-hero px-5 py-8 sm:px-8 sm:py-10 lg:min-h-[480px] lg:px-12 lg:py-12"><div className="home-hero-grid relative grid items-center gap-9 lg:grid-cols-[minmax(0,0.95fr)_minmax(420px,1.05fr)] lg:gap-6"><div className="flex max-w-2xl flex-col items-start gap-6"><Badge variant="outline"><Sparkles data-icon="inline-start" />Tu catálogo, más claro</Badge><div className="flex flex-col gap-4"><h1 className="text-balance text-4xl font-semibold leading-[1.02] tracking-[-0.04em] sm:text-5xl lg:text-6xl">Elegí mejor. <span className="text-primary">Compará con criterio.</span></h1><p className="max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">Buscá entre productos reales, explorá sus características y encontrá la opción que encaja con lo que necesitás.</p></div><form action="/assistant" className="flex w-full max-w-xl flex-col gap-3" method="get"><label className="sr-only" htmlFor="home-search">¿Qué producto estás buscando?</label><InputGroup className="h-12 bg-card shadow-sm"><InputGroupAddon><Search aria-hidden="true" /></InputGroupAddon><InputGroupInput id="home-search" name="q" pattern=".*\\S.*" placeholder="Ej.: auriculares WH-1000XM6" required title="Escribí una búsqueda" /><InputGroupAddon align="inline-end"><InputGroupButton type="submit" size="sm" variant="default">Buscar<ArrowRight data-icon="inline-end" /></InputGroupButton></InputGroupAddon></InputGroup></form></div><div className="relative mx-auto w-full max-w-2xl lg:max-w-none" aria-hidden="true"><div className="absolute inset-[14%] rounded-full bg-primary/20 blur-3xl" /><Image className="relative h-auto w-full object-contain drop-shadow-2xl" src="/images/shopai-laptop-hero.webp" alt="" width={1200} height={800} preload sizes="(max-width: 1023px) 90vw, 48vw" /></div></div></section>{children}</div></main>;
}
