import Link from "next/link";
import { ArrowRight, Boxes, PackageSearch, TriangleAlert } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import { loadFeaturedProducts, loadHomeCategories } from "../_lib/home-catalog";
import type { FeaturedProducts, HomeCategory, HomeSection } from "../_types/Home";

function heading(id: string, title: string, description: string) { return <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 id={id} className="text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h2><p className="max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">{description}</p></div><Link className={cn(buttonVariants({ variant: "ghost" }), "self-start sm:self-auto")} href="/explore">Ver todo<ArrowRight data-icon="inline-end" /></Link></div>; }
function error(subject: string) { return <Alert><TriangleAlert /><AlertTitle>No pudimos cargar {subject}</AlertTitle><AlertDescription>Probá actualizar la página en unos instantes. El resto de ShopAI sigue disponible.</AlertDescription></Alert>; }
export async function HomeCategoriesSection() { let section: HomeSection<HomeCategory[]>; try { section = { data: await loadHomeCategories(), status: "success" }; } catch { section = { status: "error" }; } return <section aria-labelledby="categories-title" className="flex flex-col gap-6">{heading("categories-title", "Explorá por categoría", "Empezá por el tipo de producto y recorré el catálogo disponible.")}{section.status === "error" ? error("las categorías") : section.data.length === 0 ? <Empty className="min-h-48 border"><EmptyHeader><EmptyMedia variant="icon"><Boxes /></EmptyMedia><EmptyTitle>Todavía no hay categorías</EmptyTitle><EmptyDescription>Cuando el catálogo tenga categorías, vas a encontrarlas acá.</EmptyDescription></EmptyHeader></Empty> : <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{section.data.map((category) => <Link key={category.id} href={`/explore?${new URLSearchParams({ categoryId: category.id })}`}><Card className="h-full"><CardHeader><PackageSearch className="size-4 text-primary" /><CardTitle>{category.name}</CardTitle><CardDescription>{category.description ?? "Descubrí los productos disponibles en esta categoría."}</CardDescription></CardHeader></Card></Link>)}</div>}</section>; }
export async function HomeProductsSection() { let section: HomeSection<FeaturedProducts>; try { section = { data: await loadFeaturedProducts(), status: "success" }; } catch { section = { status: "error" }; } return <section aria-labelledby="products-title" className="flex flex-col gap-6">{heading("products-title", "Productos destacados", "Una selección directa del catálogo actual para empezar a comparar.")}{section.status === "error" ? error("los productos destacados") : section.data.items.length === 0 ? <Empty className="min-h-56 border"><EmptyHeader><EmptyMedia variant="icon"><PackageSearch /></EmptyMedia><EmptyTitle>Todavía no hay productos</EmptyTitle><EmptyDescription>Los primeros productos del catálogo aparecerán en esta sección.</EmptyDescription></EmptyHeader></Empty> : <div className="flex flex-col gap-4">{section.data.hasPartialFailure ? <Alert><TriangleAlert /><AlertTitle>Algunos detalles no están disponibles</AlertTitle><AlertDescription>Mostramos los productos que pudimos cargar; alguna imagen o precio puede faltar.</AlertDescription></Alert> : null}<div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{section.data.items.map((product) => <Link key={product.id} href={`/compare?${new URLSearchParams({ productId: product.id })}`}><Card className="h-full"><CardHeader><CardTitle>{product.name}</CardTitle><CardDescription>{product.description ?? "Consultá sus características y comparalo con otras opciones."}</CardDescription></CardHeader></Card></Link>)}</div></div>}</section>; }
export function HomeCategoriesSkeleton() { return <section aria-label="Cargando categorías" className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-40" />)}</section>; }
export function HomeProductsSkeleton() { return <section aria-label="Cargando productos" className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <Skeleton key={index} className="h-48" />)}</section>; }
